[package]
name = "sudoku"
version = "0.1.0"
authors = ["Flecheck <bessou.mathieu@gmail.com>"]
edition = "2018"

[dependencies]
lazy_static = "1.4.0"
keyed_priority_queue = "0.2.1"
bit-set = "0.5.2"
itertools = "0.9.0"
array-macro = "1.0.5"