[package]
name = "sudoku"
version = "0.1.0"
authors = ["Flecheck <bessou.mathieu@gmail.com>"]
edition = "2018"

[dependencies]
lazy_static = "1.0.1"
priority-queue = "0.5.1"
bit-set = "0.5.0"
itertools = "0.7.8"
